### PR TITLE
Multiple replace with tests

### LINKED ISSUE #306: Cannot stub more than 1 element?
When I tried to use replace() multiple times to stub out multiple elements, sinon complains:

> Error: Attempted to wrap instanceTemplate which is already wrapped
>     Object.wrapMethod at /components/sinon/sinon-1.12.1.js:1210
>           Object.stub at /components/sinon/sinon-1.12.1.js:3007
>           Object.with at web-component-tester/browser.js:1555
> 

Is replace() designed to be used more than once? Or is it only limited to only stub out 1 element?

### PR DESCRIPTION
**Pull request by e111077**
Branched off of #310. Fixes #306.

### CODE REVIEW

File: browser/mocha/replace.js [hunk 1]
```diff
@@ -22,6 +22,10 @@ extendInterfaces('replace', function(context, teardown) {
         // implementation for later:
         var originalInstanceTemplate = Polymer.Base.instanceTemplate;
 
+        if (Polymer.Base.instanceTemplate.isSinonProxy) {
```
Comment (justinfagnani) [inline browser/mocha/replace.js]: Is the change we discussed yesterday still the plan here?

Comment (e111077) [inline browser/mocha/replace.js]: I added a comment in the last PR before closing it:

Further investigation shows that Sinon's API does not seem to support replacing the wrapped spy. Also looking at their GH for this function, it seems as if replacing it manually would just repeat their already-written code. I recommend that we restore if it is already wrapped in a spy. (stay the same)

WDYT?

Comment (justinfagnani) [inline browser/mocha/replace.js]: So I'm not suggesting that the wrapper is replaced, I'm suggesting that we only stub `instanceTemplate` once, with a stub that's actually capable of replacing multiple elements. This way we don't have a stub calling a stub calling a stub, each doing a querySelector and replace. It would have to be slightly rewritten to do a tree walk rather than querySelector, but that should be relatively easy.

Comment (justinfagnani) [inline browser/mocha/replace.js]: This is what I think the stub should look like:

```javascript
var replacements = {};

sinon.stub(Polymer.Base, 'instanceTemplate', function(template) {
  var dom = originalInstanceTemplate.apply(this, arguments);
  var nodeIterator = document.createNodeIterator(dom, NodeFilter.SHOW_ELEMENT);
  var node;

  while (node = nodeIterator.nextNode()) {
    var tagName = node.tagName.toLowercase();
    if (Object.hasOwnProperty(replacements, tagName)) {
      var replacement = document.createElement(replacements[tagName]);
      node.parentNode.replaceChild(replacement, node);
    }
  }
  return dom;
});
```

Besides stubbing `instanceTemplate` only on the first call, `with` would write into `replacements`.

File: browser/mocha/replace.js [hunk 2]
```diff
@@ -18,6 +21,17 @@ extendInterfaces('replace', function(context, teardown) {
...
+        replacements[oldTagName] = tagName;
+
+        // If the function is already a stub, restore it to original
+        if (Polymer.Base.instanceTemplate.isSinonProxy) {
+          Polymer.Base.instanceTemplate.restore();
+        }
+
         // Keep a reference to the original `Polymer.Base.instanceTemplate`
         // implementation for later:
         var originalInstanceTemplate = Polymer.Base.instanceTemplate;
```
Comment (e111077) [inline browser/mocha/replace.js]: @justinfagnani note: this is now after the restore and thus will never be a stub.

Comment (justinfagnani) [inline browser/mocha/replace.js]: I don't think you ever need to restore though...

Comment (e111077) [inline browser/mocha/replace.js]: good point; it's all pointers at this point!

fixed

File: browser/mocha/replace.js [hunk 3]
```diff
@@ -18,6 +21,17 @@ extendInterfaces('replace', function(context, teardown) {
   return function replace(oldTagName) {
     return {
       with: function(tagName) {
+        // Standardizes our replacements map
+        oldTagName = oldTagName.toLowerCase();
+        tagName = tagName.toLowerCase();
+
+        replacements[oldTagName] = tagName;
+
+        // If the function is already a stub, restore it to original
```
Comment (justinfagnani) [inline browser/mocha/replace.js]: update comment

File: browser/mocha/replace.js [hunk 4]
```diff
@@ -27,27 +41,34 @@ extendInterfaces('replace', function(context, teardown) {
           // The DOM to replace is the result of calling the "original"
           // `instanceTemplate` implementation:
           var dom = originalInstanceTemplate.apply(this, arguments);
+          // creates an iterator of the node tree
```
Comment (justinfagnani) [inline browser/mocha/replace.js]: This comment doesn't add much information to the line of code. The only wood not int he code is "tree" :P

File: browser/mocha/replace.js [hunk 5]
```diff
@@ -27,27 +41,34 @@ extendInterfaces('replace', function(context, teardown) {
...
-          var nodes = Array.prototype.slice.call(dom.querySelectorAll(oldTagName));
+          // Traverses the tree. A recently-replaced node will be put next, so
+          // if a node is replaced, it will be checked if it needs to be
+          // replaced again.
+          while (node = nodeIterator.nextNode()) {
+            var currentTagName = node.tagName.toLowerCase();
 
-          // For all of the nodes we want to place...
-          nodes.forEach(function(node) {
+            // If this node is in our replacements map...
```
Comment (justinfagnani) [inline browser/mocha/replace.js]: remove comment

**Comment by justinfagnani** [comment]
LGTM after the last little nits. Thanks!

**Comment by hungyao** [comment]
This does not seem to solve the issue observed in https://github.com/Polymer/web-component-tester/pull/294#issuecomment-191286622

replaced() elements are still being imported into the document (and causing unwanted sideeffects).
